name: smartwarehouse_ocr_rfid
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  camera: ^0.8.1
  crop_your_image: ^0.5.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  firebase_core: ^1.1.0
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_bluetooth_serial: ^0.2.2
  flutter_easyloading: ^3.0.0
  flutter_native_splash: ^1.1.8+4
  flutter_redux: ^0.8.2
  flutter_slidable: ^1.0.0-dev.2
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  google_ml_kit: ^0.5.0
  http: ^0.13.1
  image: ^3.0.2
  image_cropper: ^1.4.0
  image_picker: ^0.8.0
  input_with_keyboard_control: ^1.0.7
  modal_bottom_sheet: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  redux: ^5.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  slider_button: ^1.0.0
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/pp-construction-&-investment.png
    - assets/logos/widya-robotics.png
    - assets/logos/wii-robotics.png
    - assets/logos/wii.png
    - assets/images/ocr_icon2.png
    - assets/images/rfid.png
    - assets/images/shutter_ocr.png
    - assets/images/shutter.png
    - assets/jajal.json
    - assets/logos/Logout-Button.png
    - assets/images/OCR-Icon.png
    - assets/images/RFID-Icon.png
    - assets/images/header-login.png
    - assets/images/sticker_tag.png
    - assets/images/Pairing-Illustration.png
    - assets/logos/ocr_icon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Anodina
      fonts:
        - asset: assets/fonts/Anodina-Bold.otf
          weight: 700
        - asset: assets/fonts/Anodina-Light.otf
          weight: 200
        - asset: assets/fonts/Anodina-Regular.otf
          weight: 400
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/Roboto-Light.otf
    #       weight: 200
    #     - asset: assets/fonts/Roboto-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/Roboto-Medium.otf
    #       weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
